language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
    - php: nightly
    - php: 5.4
      env: COMPOSER_OPTIONS="--prefer-lowest"
    - php: 5.4
      env: $SYMFONY_VERSION="~2.7.0"
    - php: 5.4
      env: $SYMFONY_VERSION="~2.8.0"
    - php: 5.5.9
      env: $SYMFONY_VERSION="^3.0.0"

before_install:
  - 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;'

install: composer update --prefer-source --no-interaction --no-progress ${COMPOSER_OPTIONS}

script: bin/phpunit -v

notifications:
  email: false
